from time import sleep
import sys
container = 0
sleepDur = 1
gameRunning  = True


input("Welcome, choose you difficulty: Gentle (1), Mean (2), Troublesome(3), and Adorable(4): ")
print("You know what... It was completly useless. This game only has 1 difficulty")
print("Sorry for that. Good luck")
x = input("What's your name my friend? ")
print("OK, give me a second")
sleep(1)
if x.lower() == "krbec" or x.lower() == "jaroslav":
    print("GG, you won :)")
    sys.exit()
    #END 1
else:
    print("You know what... Nevermind.")
sleep(2)

print("INTRO")
print("\n\n Welcome to the game!\n \nYou have to walk through the labyrinth and find your way out. Along the way you will encounter various obstacles and puzzles that you must overcome. ")
sleep(7*sleepDur)
print("STORY:   One day you wake up in a dark room. You have no idea where you are or how you got there. All you know is that you have to find a way out.\nSTORY:   By feel, you'll find a flashlight to help you see in the dark.")
sleep(1*sleepDur)
print("STORY:   You turn on the light, and all you see is white.")
sleep(2*sleepDur)
print("STORY:   After a while you get used to the light and stand in the room. The walls are made of stone bricks, the only thing in the room is a 'bed'. Actually, it's a very cheap-looking mattress.")
sleep(2*sleepDur)
print("STORY:   You turn behind you, you see a door. A door with no handle. There's a hole in the door where it should be.")

print("Here comes your first decision: (1) You look out through the hole. (2) You run with all your might towards the door, thinking you're going to break it down.")

while gameRunning:
    dec = input("Your decision (1/2): ")
    if dec.lower() == "1":
        print("You put one eye to the hole. All you see is black. So you gonna try the door?")
        dec = input("Try it? (y/n)")
        if dec.lower() == "n":
            print("GAME OVER \n You stayed in the room until you died from lack of water. ")
            sys.exit()
            # END 2
        container = 1
    elif dec == "2" or dec.lower() == "y":
        print("You rammed it into the door with all his might. You ripped the door open and found yourself in a huge hallway.")
        sleep(1*sleepDur)
        print("You find yourself in a dimly lit hallway. The walls are made of the same stone bricks as before. There are doors on both sides of the hallway.")
        sleep(1*sleepDur)
        print("Which door do you choose? (L) The door on the left. (R) The door on the right.")
    
    
    dec = input("Your decision (l/r): ")
    if dec.lower() == "l":
        print("You entered the room on the left. It's a small room with a single bed in it. The bed is unmade and there are some clothes on the floor.\n")
        sleep(1*sleepDur)
        print("You see a small window in the room. Do you want to investigate it? (y/n)")
        dec = input("Investigate the window? (y/n)")
        if dec.lower() == "y":
            print("You approach the window and see that the window leads to a balcony. You can see the city lights twinkling below you.")
            sleep(1*sleepDur)   
            print("You open the window and climb out onto the balcony. You can see the city lights twinkling below you. You can also see a river flowing nearby.")
            sleep(1*sleepDur)
            print("Do you want to go back inside or keep exploring?")
            dec = input("Go back inside or keep exploring? (i/e): ")
            if dec.lower() == "i":
                print("You go back inside the room and close the window. You decide to do nothing.")
                sleep(1*sleepDur)
                print("GAME OVER \n You stayed in the room until you died from lack of water. ")
                #END WATER
                sys.exit()
            elif dec.lower() == "e":
                print("You decide to keep exploring. You find a way down to the ground and start walking along the riverbank.")
                sleep(1*sleepDur)
                print("After a while, you come across a small hut. Do you want to investigate it? (y/n)")
                dec = input("Investigate the hut?(y/n) ")
                if dec.lower() == "y":
                    print("You approach the hut and find a small partially bald man sitting outside. He seems friendly and offers you some water.")
                    print("Do you want to accept his offer? (y/n)")
                    dec = input("Accept the water? ")
                    if dec.lower() == "y":
                        print("You drink the water and feel refreshed. The partially bald man tells you that he knows where you are, and he will hire you to his small cofee shop..")
                        sleep(1*sleepDur)
                        print("You build up nice relationship with your chief, so you will eventually become kind of friends. One day, you will be free and manager of Mr Pavelka's coffee shop.")
                        sleep(1*sleepDur)
                        print("\n\nCongratulations! You have won the game! You are working for an partially bald man as a cashier in his store. But hey, you survived!")
                        sys.exit()
                        #END 3
                    elif dec.lower() == "n":
                        print("The old man hits you with a stick till you black out.")
                        sleep(1*sleepDur)
                        print("When you wake up, you are in some coffee shop with strange band on your hand.")
                        sleep(1*sleepDur)
                        print("The man told you, you are his slave now.")
                        sleep(1*sleepDur)
                        dec = input("Do you want to resist? (y/n): ")
                        if dec.lower() == "y":
                            print("He taps a button on his desk and you receive a electric shock from the band. The partially bald man just laught to you.")
                            print("Becouse you were not respecting me, I will send you to my coffee bean farm.")
                            print("GAME OVER \n you are now slave farming coffee for Mr. Pavelka")
                            sys.exit()
                            #END 4
                        elif dec.lower() == "n":
                            print("You build up nice relationship with your chief, so you will eventually become kind of friends. One day, you will be free and manager of Mr. Pavelka's coffee shop.")
                            sys.exit()
                            #END 3
                elif dec.lower() == "n":
                    print("You decide not to explore further.")
                    sleep(1*sleepDur)
                    print("From the heaven falls big metal object, that you cannot identify.")
                    sleep(1*sleepDur)
                    print("When it's getting closer, you see how big it is.")
                    sleep(1*sleepDur)
                    print("You say: 'Jesus Christ on a motor bike! That is an enourmous giant fucking anvil.' you say out loud as it crushes you down into the ground")
                    sleep(1*sleepDur)
                    print("GAME OVER \n You died, but it's coolest way to die. So it's kinda win, innit'.")
                    sys.exit()
                    #END 5

        elif dec.lower() == "n":
            print("You decided to walk out of this room and continue down the hallway.")
            dec = input("Do you want to investigate the second room? (y/n): ")
            if dec.lower() == "n":
                print("You continued down the hallway.")
                sleep(1*sleepDur)
                print("After about 5 minutes of walking, you see some guy.")
                sleep(1*sleepDur)
                print("You are happy to see some human after all that long time")
                sleep(1*sleepDur)
                print("You are shouting: 'Hey, where are we?")
                sleep(1*sleepDur)
                print("The guys doesn't see very friendly. He has both hands in pockets.")
                sleep(1*sleepDur)
                print("You explained that you are here, and you escaped from some really bad looking room")
                sleep(1*sleepDur)
                print("Suddenly the guy take his gun out, and start shouting at you.")
                sleep(1*sleepDur)
                print("He says: Stop right there. Don't make any sudden moves. One move and I'll shoot you fucking brain out")
                sleep(1*sleepDur)
                print("You accidentaly coughed, so he shoot your head with his Glock-17 Gen4")
                sleep(1*sleepDur)
                print("GAME OVER \n Your head has hole right through. (So you died BTW)")
                sys.exit()
                #END 6
    elif dec.lower() == "r":
        print("You can now see, why were this door opened.")
        sleep(1*sleepDur)
        print("There is pretty big hole under the toilet.")
        sleep(1*sleepDur)
        print("It's that big, that you could stuff yourself in there and get out.")
        sleep(1*sleepDur)
        print("But you don't know, what's on the second end of the hole")
        sleep(1*sleepDur)
        dec =input("Do you wanna risk it? (y/n):")
        if dec.lower() == "y":
            print("You took a deep breath and jumped into the hole.")
            sleep(1*sleepDur)
            print("And then you felt something hard against your backside.")
            sleep(1*sleepDur)
            print("Then you fell forward and hit your face against the ground.")
            sleep(1*sleepDur)
            print("You feel like you have been trampled by a herd of elephants.")
            sleep(1*sleepDur)
            print("GAME OVER \n You got crushed or stomped or whatever they do when they step on you.")
            sys.exit()
            #END 7
        elif dec.lower() =="n":
            print("You decided to stay away from the hole.")
            sleep(1*sleepDur)
            print("You walked around the corner, and found another door.")
            sleep(1*sleepDur)
            print("This one was locked, but you managed to crack the lock with your flashlight.")
            sleep(1*sleepDur)
            print("On the other side of the door, you saw a bright light.")
            sleep(1*sleepDur)
            print("You entered the room, and found yourself in a large, empty space.")
            sleep(1*sleepDur)
            print("In the center of the room, there was a table with candles.")
            sleep(1*sleepDur)
            print("They were lit, and their flames flickered in the dark air.")
            sleep(1*sleepDur)
            print("Around the table, there were people sitting in chairs.")
            sleep(1*sleepDur)
            print("All of them had eyes closed, and they seemed to be asleep.")
            sleep(1*sleepDur)
            print("One of them suddenly opens his eyes, looks at you, and smiles.")
            sleep(1*sleepDur)
            print("He says: 'Welcome to our home.'")
            sleep(1*sleepDur)
            print("You look around, trying to figure out who these people might be.")
            sleep(1*sleepDur)
            print("You noticed that everyone else seems to be blindfolded except for one person.")
            sleep(1*sleepDur)
            print("That person is holding a small knife, and he points it at you.")
            sleep(1*sleepDur)
            print("Everyone starts laughing.")
            sleep(1*sleepDur)
            print("Someone unblindfolds himself, revealing a man with a scar across his cheekbone.")
            sleep(1*sleepDur)
            print("He introduces himself as John Otto.")
            sleep(1*sleepDur)
            print("John explains that they are a group of survivors, and they need your help.")
            sleep(1*sleepDur)
            print("And when new guy appears, they need to fight the oldest member.")
            sleep(1*sleepDur)
            print("Oldest member is named Mr. Krbec.")
            sleep(1*sleepDur)
            print("Mr. Krbec is standing up, and he is not happy.")
            sleep(1*sleepDur)
            print("He shouts: 'I will kill you!')")
            sleep(1*sleepDur)
            print("John tries to calm him down, saying that you won't hurt anyone.")
            sleep(1*sleepDur)
            print("Mr. Krbece continues to rant about how you killed his family.")
            sleep(1*sleepDur)
            print("John tells you that you must defeat Mr. Krbec before anything happens.")
            sleep(1*sleepDur)
            print("You decide to go ahead and prepare for battle.")
            dec=input("Are you ready to fight? (y/n): ")
            if dec.lower()=="y":
                print("You charged towards Mr. Krbec, ready to kick some ass.")
                sleep(1*sleepDur)
                print("However, just as you reached him, you heard a loud noise behind you.")
                sleep(1*sleepDur)
                print("A massive creature emerged from the darkness, its eyes glowing red.")
                sleep(1*sleepDur)
                print("He said: 'Come'on JS, we've got some work to do.")
                sleep(1*sleepDur)
                print("The creature jumped on you, and smashed you to the ground.")
                sleep(1*sleepDur)
                print("GAME OVER \n You got eaten alive by the monster.")
                sleep(1*sleepDur)
                print("But there is the moral of the story. Never EVER try to fight Mr. Krbec")
            elif dec.lower() == 'n':
                print("You turn and run away from the danger.")
                sleep(1*sleepDur)
                print("As you run, you hear footsteps behind you.")
                sleep(1*sleepDur)
                print("Suddenly, you stop dead still.")
                sleep(1*sleepDur)
                print("There stands an old man, dressed in black robes.")
                sleep(1*sleepDur)
                print("He has a long white beard, and a staff in hand.")
                sleep(1*sleepDur)
                print("He says: 'Hello, young one. I see you're lost.")
                sleep(1*sleepDur)
                print("Follow me, and I may be able to guide you through this wilderness.")
                sleep(1*sleepDur)
                print("But remember: always trust those who wear black.")
                sleep(1*sleepDur)
                print("You noded your head, so you dont need to go back to the fight.")
                sleep(1*sleepDur)
                print("This guys seems to be lot stronger than your oponent Krbec")
                sleep(1*sleepDur)
                print("So you follow him into the unknown.")
                sleep(1*sleepDur)
                print("After ages of walking through the tunnel, you see light")
                sleep(1*sleepDur)
                print("You see some village.")
                sleep(1*sleepDur)
                print("The old man says: 'Now it's on you'")
                sleep(1*sleepDur)
                print("After a while, you come across a small hut. Do you want to investigate it? (y/n)")
                dec = input("Investigate the hut?(y/n) ")
                if dec.lower() == "y":
                    print("You approach the hut and find a small partially bald man sitting outside. He seems friendly and offers you some water.")
                    sleep(1*sleepDur)
                    print("Do you want to accept his offer? (y/n)")
                    dec = input("Accept the water? ")
                    if dec.lower() == "y":
                        print("You drink the water and feel refreshed. The partially bald man tells you that he knows where you are, and he will hire you to his small cofee shop..")
                        sleep(1*sleepDur)
                        print("You build up nice relationship with your chief, so you will eventually become kind of friends. One day, you will be free and manager of Mr. Pavelka's coffee shop.")
                        sleep(1*sleepDur)
                        print("\n\nCongratulations! You have won the game! You are working for an partially bald man as a chashier in his store. But hey, you survived!")
                        sys.exit()
                        #END 3
                    elif dec.lower() == "n":
                        print("The partially bald man hits you with a stick till you black out.")
                        sleep(1*sleepDur)
                        print("When you wake up, you are in some coffee shop with strange band on your hand.")
                        sleep(1*sleepDur)
                        print("The man told you, you are his slave now.")
                        sleep(1*sleepDur)
                        dec = input("Do you want to resist? (y/n): ")
                        if dec.lower() == "y":
                            print("He taps a button on his desk and you receive a electric shock from the band. The partially bald man just laught to you.")
                            sleep(1*sleepDur)
                            print("Becouse you were not respecting me, I will send you to my coffee bean farm.")
                            sleep(1*sleepDur)
                            print("GAME OVER \n you are now slave farming coffee for Mr Pavelka")
                            sleep(1*sleepDur)
                            sys.exit()
                            #END 4
                        elif dec.lower() == "n":
                            print("You build up nice relationship with your chief, so you will eventually become kind of friends. One day, you will be free and manager of Mr. Pavelka's coffee shop.")
                            sys.exit()
                            #END 3